# This file was generated by the script "generate_uoms.py" in the same directory.
# It contains a lookup table for UOMs used in ZUGFeRD/Factur-X.

import json
import lzma
import os

# Load the UOM map from the LZMA-compressed JSON file.
with open(
	os.path.join(os.path.dirname(os.path.realpath(__file__)), "uom_map.json.xz"), "rb"
) as file:
	uom_map = json.loads(lzma.decompress(file.read()).decode("utf-8"))

fallback_code = "C62"
